/**
 * Sql Keywords const
 */
export declare enum SqlKeys {
    USE = "USE",
    CREATE_DATABASE = "CREATE DATABASE",
    DROP_TABLE = "DROP TABLE",
    IF_EXISTS = "IF EXISTS",
    CREATE_TABLE = "CREATE TABLE",
    INSERT = "INSERT INTO",
    VALUES = "VALUES",
    UPDATE = "UPDATE",
    SET = "SET",
    DELETE = "DELETE",
    SELECT = "SELECT",
    FROM = "FROM",
    WHERE = "WHERE",
    AND = "AND",
    OR = "OR",
    GROUP = "GROUP BY",
    ORDER = "ORDER BY",
    BETWEEN = "BETWEEN",
    IN = "IN",
    NOT = "NOT",
    LIKE = "LIKE",
    AS = "AS",
    REGEXP = "REGEXP",
    IS = "IS",
    NULL = "NULL",
    LIMIT = "LIMIT",
    COUNT = "COUNT(*)",
}
